services:
  app:
    build: .                       # construïm imatge des del Dockerfile
    container_name: appiso2-app
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"               # host:contenidor
    volumes:
      - ./db.json:/app/db.json     # només persistim les dades
    restart: unless-stopped