services:
  - type: web
    name: crud-students-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: db-storage
      mountPath: /opt/render/project/src
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
